[zh] 访问网站时会发生什么？网络运行原理详解
freeCodeCamp/news-translation-tasks pull request #543
Opened 2024-11-27 01:50 UTC by dethan3

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #539

2024-11-27 12:28 UTC, miyaliu666 requested changes

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![Example of a valid URL, including its scheme, authority, path to resource, two parameters and an anchor.](https://cdn.hashnode.com/res/hashnode/image/upload/v1731414821178/970907db-f349-421e-b410-4
```suggestion
![一个有效的 URL 示例，包括其机制、授权、资源路径、两个参数和一个锚点。](https://cdn.hashnode.com/res/hashnode/image/upload/v1731414821178/970907db-f349-421e-b410-45f4ee978e0b.jpeg)
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +- **协议**： URL 的第一部分表明应该使用什么协议来获取资源。网站使用 HTTP 和 HTTPS 协议，我们稍后会详细介绍。协议后面的 `:` 用来分隔 URL 的下一部分。
```suggestion
- **机制**： URL 的第一部分表明应该使用什么协议来检索资源。网站使用 HTTP 和 HTTPS 协议，我们稍后会详细介绍。协议后面的 `:` 将其与 URL 的下一部分分隔开。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![The four-layer model includes the application layer, the transport layer, the internet layer， and the network layer. Data travels back and forth through these layers.](https://cdn.hashnode.com/res/
```suggestion
![四层模型包括应用层、传输层、互联网层和网络接口层。数据在这些层间来回传输。](https://cdn.hashnode.com/res/hashnode/image/upload/v1731414848576/178ce64e-2216-487a-b142-c88c2125dcde.jpeg)
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +TCP 包含一些功能，使其在大多数基于互联网的应用程序中普遍存在，所以让我们关注它。
```suggestion
TCP 包含一些功能，使其在大多数基于互联网的应用程序中普遍存在，所以我们重点讨论它。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +2. **头部**： 一组键值对，可以是应用于整个消息的通用头部;提供服务器状态附加信息的响应头部;或描述消息数据格式和编码(如果存在)的表示头部。
```suggestion
2. **标头**： 一组键值对，可以是应用于整个消息的通用标头、提供服务器状态附加信息的响应标头或描述消息数据格式和编码（如果存在）的表示标头。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +响应还将包含 HTTP 头部列表和响应主体，包括请求页面对应的 HTML 代码。
```suggestion
响应还将包含 HTTP 标头列表和响应主体，包括请求页面对应的 HTML 代码。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +HTTPS 的主要目的是确保数据隐私、完整性和身份识别。这意味着确保数据只能被预期的接收者访问，不能被中间人截获或修改。同时，发送者和接收者都可以被合法机构识别为他们声称的身份。
```suggestion
HTTPS 的主要目的是确保数据隐私、完整性和身份识别。这意味着确保数据只能被预期的接收者访问，不能被中间人截获或修改。同时，发送者和接收者都可以通过合法的权威机构确认其身份。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![Steps in the SSL Handshake.](https://cdn.hashnode.com/res/hashnode/image/upload/v1731414891509/541f6b6c-ad54-4301-834a-1056aea524c0.jpeg)
```suggestion
![SSL 握手的步骤](https://cdn.hashnode.com/res/hashnode/image/upload/v1731414891509/541f6b6c-ad54-4301-834a-1056aea524c0.jpeg)
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +- **认证和预主密钥**： 客户端通过相应的可信机构验证服务器的 SSL 证书，然后使用服务器的公钥(之前在证书中共享)创建预主密钥并与服务器共享。
```suggestion
- **认证和预主密钥**： 客户端通过相应的可信机构验证服务器的 SSL 证书，然后使用服务器的公钥（之前在证书中共享）创建预主密钥并与服务器共享。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    <meta name="viewport" content="width=device-width， initial-scale=1.0">
```suggestion
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    <meta name="viewport" content="width=device-width， initial-scale=1.0">
这部分代码中的标点符号应该是半角字符，不需要修改为全角字符

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +                The Internet is a huge network of interconnected computers. The World Wide Web (aka web) is built on top of that technology， as well as other services such as email， chat systems， or
```suggestion
                The Internet is a huge network of interconnected computers. The World Wide Web (aka web) is built on top of that technology, as well as other services such as email, chat systems, or file sharing.
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +            <p>Computers connected to the internet are either：</p>
```suggestion
            <p>Computers connected to the internet are either:</p>
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +                    <p>Clients， the web user's devices and the software that those devices use to access the web.</p>
```suggestion
                    <p>Clients, the web user's devices and the software that those devices use to access the web.</p>
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +                    <p>Servers， computers that store web pages， sites， or apps and the files they need to be displayed in the user's web browser or devices.</p>
```suggestion
                    <p>Servers, computers that store web pages, sites, or apps and the files they need to be displayed in the user's web browser or devices.</p>
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    box-sizing： border-box;
```suggestion
    box-sizing: border-box;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    font-family： Arial， sans-serif;
```suggestion
    font-family: Arial, sans-serif;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    background-color： #f4f4f9;
```suggestion
    background-color: #f4f4f9;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    color： #333;
```suggestion
    color: #333;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    padding： 20px;
```suggestion
    padding: 20px;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    max-width： 800px;
```suggestion
    max-width: 800px;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    margin： 0 auto;
```suggestion
    margin: 0 auto;
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    margin： 0 auto;
这部分代码的标点符号也应该是半角，有点多，我在发布文章时直接修改吧。

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![The CSSOM tree includes each HTML element and their corresponding styles. ](https://cdn.hashnode.com/res/hashnode/image/upload/v1731496962735/f3cb0399-a9fb-48cc-8043-00608d1236db.jpeg)
```suggestion
![CSSOM 树包括每个HTML元素及其对应的样式。](https://cdn.hashnode.com/res/hashnode/image/upload/v1731496962735/f3cb0399-a9fb-48cc-8043-00608d1236db.jpeg)
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![A unordered list selected and the accessibility tab in Chrome Dev Tools.](https://cdn.hashnode.com/res/hashnode/image/upload/v1731578933460/0a8c7a78-c19a-4d19-a96a-fabd19772156.png)
```suggestion
![Chrome 开发者工具中的无序列表及辅助功能选项卡。](https://cdn.hashnode.com/res/hashnode/image/upload/v1731578933460/0a8c7a78-c19a-4d19-a96a-fabd19772156.png)
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![A unordered list selected and the accessibility tab in Firefox Dev Tools.](https://cdn.hashnode.com/res/hashnode/image/upload/v1731579023128/85aeb312-1632-49c3-80cb-0d5db8ec8502.png)
```suggestion
![Firefox 开发者工具中的无序列表及辅助功能选项卡。](https://cdn.hashnode.com/res/hashnode/image/upload/v1731579023128/85aeb312-1632-49c3-80cb-0d5db8ec8502.png)
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +拥有结构良好的无障碍树对于确定网站是否可以使用辅助技术导航至关重要，这将决定包容与排除的差异。
```suggestion
拥有结构合理的可访问性树是决定网站是否可以使用辅助技术进行浏览的关键，也反映了网站是具有包容性还是排除性。
```

2024-11-27 12:28 UTC, miyaliu666 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +![The render tree is created from the DOM and CSSOM trees.](https://cdn.hashnode.com/res/hashnode/image/upload/v1731501603172/d3467e9a-e75b-4217-875b-58684edfdbc0.jpeg)
```suggestion
![渲染树是从 DOM 和 CSSOM 树创建的。](https://cdn.hashnode.com/res/hashnode/image/upload/v1731501603172/d3467e9a-e75b-4217-875b-58684edfdbc0.jpeg)
```

2024-11-27 12:30 UTC, miyaliu666 commented
谢谢 @dethan3 校对这篇文章，我写了一些修改建议，供参考。

2024-11-28 02:11 UTC, dethan3 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +- **协议**： URL 的第一部分表明应该使用什么协议来获取资源。网站使用 HTTP 和 HTTPS 协议，我们稍后会详细介绍。协议后面的 `:` 用来分隔 URL 的下一部分。
我认为【机制】不能很好的解释 "Scheme" 这个单词。斟酌之后改为了“协议类型”。

2024-11-28 02:27 UTC, dethan3 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +2. **头部**： 一组键值对，可以是应用于整个消息的通用头部;提供服务器状态附加信息的响应头部;或描述消息数据格式和编码(如果存在)的表示头部。
“标头”应该是在 HTTP 协议中对 “Header” 的统称，相应在这里应该翻译成“响应标头”，但我选择简化一点称之为“响应头”。

2024-11-28 02:36 UTC, dethan3 commented on articles/zh/what-happens-when-you-visit-a-website.md
> +    <meta name="viewport" content="width=device-width， initial-scale=1.0">
我不应该用全局替换的😭

2024-11-28 05:24 UTC, merged